# Generated by Django 4.0.4 on 2022-05-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('label', models.TextField()),
            ],
            options={
                'db_table': 'image_data',
            },
        ),
    ]
