# Generated by Django 4.0.4 on 2022-05-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_viewer', '0002_image_data_check_count_alter_image_data_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_data',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
